Implement `std::pair` and `std::array`
managarm/cxxshim pull request #19
Opened 2024-05-31 17:58 UTC by no92

This is needed by the new bragi additions for managarm/mlibc.

2024-05-31 18:12 UTC, ElectrodeYT approved these changes
LGTM

2024-05-31 19:44 UTC, Qwinci requested changes
Looks fine to me (not taking the missing std functions into account) other than a few const related issues.

2024-05-31 19:44 UTC, Qwinci commented on stage2/include/array
> +	[[nodiscard]] pointer data() const noexcept {
This should return a const_pointer (which is a typedef to const element *).

2024-05-31 19:44 UTC, Qwinci commented on stage2/include/array
> +	[[nodiscard]] iterator begin() const noexcept {
Same here, except const_iterator.

2024-05-31 19:44 UTC, Qwinci commented on stage2/include/array
> +	[[nodiscard]] iterator end() const noexcept {
Same here.

2024-05-31 19:44 UTC, Qwinci commented on stage2/include/array
> +	[[nodiscard]] element &operator[](std::size_t n) noexcept {
Might be nice to add the const ref variant of this too.

2024-05-31 19:50 UTC, no92 commented
Addressed the comments raised, and added implementations of `max_size()` and `empty()`.

2024-05-31 19:55 UTC, Qwinci approved these changes

2024-05-31 19:58 UTC, merged

2024-05-31 21:40 UTC, ArsenArsen commented on stage2/include/array
> +template<typename element, std::size_t count>
these should be UpperCamelCase

2024-06-01 07:47 UTC, no92 commented on stage2/include/array
> +template<typename element, std::size_t count>
See #20.